all: 
# javac *.java

run: 
	python main.py
# java -cp . Main

clean:
	rm -f *.pyc __pycache__/* *.zip
# rm *.class

zip:
	zip -r Trabalho-1-Tabuleiro.zip *.py
# zip -r Trabalho-1-Tabuleiro.zip *.java